### ISSUE TITLE
DiffFormatter.appendEqualBlock: SIOOBE

### ISSUE THREAD

**Issue by mstrap** [aibtra/aibtra#10]
```
2024-11-16T12:27:35.6386059 [pool-1-thread-20] SEVERE: Range [2787, 2786) out of bounds for length 3797
java.lang.StringIndexOutOfBoundsException: Range [2787, 2786) out of bounds for length 3797
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at dev.aibtra.diff.DiffFormatter.appendEqualBlock(DiffFormatter.kt:118)
	at dev.aibtra.diff.DiffFormatter.format(DiffFormatter.kt:40)
	at dev.aibtra.diff.DiffManager$updateState$1.invoke(DiffManager.kt:212)
	at dev.aibtra.diff.DiffManager$updateState$1.invoke(DiffManager.kt:201)
	at dev.aibtra.gui.SequentialRunner$schedule$1$2.invokeSuspend(SequentialRunner.kt:33)
	at dev.aibtra.gui.SequentialRunner$schedule$1$2.invoke(SequentialRunner.kt)
	at dev.aibtra.gui.SequentialRunner$schedule$1$2.invoke(SequentialRunner.kt)
	at dev.aibtra.gui.SequentialRunner$launchSafe$1.invokeSuspend(SequentialRunner.kt:54)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by mstrap** [comment]
Once more:

```
2024-11-21T20:54:55.7295698 [pool-1-thread-6] SEVERE: Range [2327, 2326) out of bounds for length 3784
java.lang.StringIndexOutOfBoundsException: Range [2327, 2326) out of bounds for length 3784
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
```
